name: Build and Deploy Hugo Site

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build Hugo site
        run: hugo

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Fix Hugo 4 GitHub
        run: |
          sed -i '4i baseURL: "https://ilmenauerschachverein.github.io/IlmenauerOpen2024/"' hugo.yaml

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public' 
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
