name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.20'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Cache Hugo Modules
        uses: actions/cache@v4
        with:
          path: .hugo_mod/cache
          key: ${{ runner.os }}-hugo-mod-${{ hashFiles('**/go.mod') }}
          restore-keys: |
            ${{ runner.os }}-hugo-mod-

      - name: Hugo Dependencies
        run: hugo mod get

      - name: Build Hugo
        run: |
          sed -i 's/^baseURL.*/baseURL = "https:\/\/open24.ilmenauer-schachverein.de\/"/' hugo.yaml
          hugo --cleanDestinationDir
          find . -mindepth 1 -not -name 'public' -not -path './public/*' -exec rm -rf {} +
          mv public/* .
          rm -rf public


      - name: Upload to Server via SCP
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          source: "*"
          target: "/var/www/ilmenauerschachverein/open24"
          rm: true  
